apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-metrics-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  namespace: go-test
  labels:
    app: go-git-git-metrics
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: git-metrics
  endpoints:
  - port: "8080"
    path: "/metrics"
